/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef JPEGCache_CONSTANTS_H
#define JPEGCache_CONSTANTS_H

#include "JPEGCache_types.h"

namespace JPEGCache {

class JPEGCacheConstants {
 public:
  JPEGCacheConstants();

};

extern const JPEGCacheConstants g_JPEGCache_constants;

} // namespace

#endif
