/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "JPEGCache_constants.h"

namespace JPEGCache {

const JPEGCacheConstants g_JPEGCache_constants;

JPEGCacheConstants::JPEGCacheConstants() {
}

} // namespace

